// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 0,
    name: "",
    age: "Default Profile",
    on: true,
    img: "https://www.baytekent.com/wp-content/uploads/2016/12/facebook-default-no-profile-pic1.jpg",
    inOffice: false,
    vacationDaysRemaining: 0,
    phone: "",
    position: "",
    wfh: false,
    address: "Address & Phone",
    review: "",
  },

  {
    id: 1,
    name: "Racheal Fisher",
    age: 41,
    on: false,
    img: "https://mydmi.imgix.net/AddisonRae.png?fm=jpg&ixlib=php-3.3.1&q=40&w=652&s=b086f4cb5b251efcae9f8dbea97e1627",
    inOffice: false,
    vacationDaysRemaining: 10,
    phone: "345 - 5345",
    position: "Frontend Software Developer",
    wfh: false,
    address: "200 Birchmount St, London ON",
    review: "Review Due on 12 July 2023",
  },
  {
    id: 2,
    name: "Alex Goldberg",
    age: 19,
    on: false,
    img: "https://image.shutterstock.com/mosaic_250/2780032/1667439913/stock-photo-headshot-portrait-of-smiling-millennial-male-employee-talk-on-video-call-or-web-conference-in-1667439913.jpg",
    inOffice: false,
    vacationDaysRemaining: 13,
    phone: "865 - 6675",
    position: "Customer Service",
    wfh: false,
    address: "32 Laird Dr, Trenton ON",
  },
  {
    id: 3,
    name: "Sam Hodgson",
    age: 33,
    on: false,
    img: "https://media.istockphoto.com/photos/millennial-male-team-leader-organize-virtual-workshop-with-employees-picture-id1300972574?b=1&k=20&m=1300972574&s=170667a&w=0&h=2nBGC7tr0kWIU8zRQ3dMg-C5JLo9H2sNUuDjQ5mlYfo=",
    inOffice: false,
    vacationDaysRemaining: 3,
    phone: "963 - 9045",
    position: "Sales Lead",
    wfh: true,
    address: "103 North Humbert Dr, Waterloo ON",
  },
  {
    id: 4,
    name: "Kevin Hamster",
    age: 25,
    on: false,
    img: "https://media.istockphoto.com/photos/headshot-portrait-of-smiling-ethnic-businessman-in-office-picture-id1300512215?b=1&k=20&m=1300512215&s=170667a&w=0&h=LsZL_-vvAHB2A2sNLHu9Vpoib_3aLLkRamveVW3AGeQ=",
    inOffice: true,
    vacationDaysRemaining: 20,
    phone: "353 - 9070",
    position: "Legal Department",
    wfh: false,
    address: "5b Deer Vally, Greenwood NS",
  },
  {
    id: 5,
    name: "James Hoffstand",
    age: 25,
    on: false,
    img: "https://content.fortune.com/wp-content/uploads/2014/10/kevinsystrom-headshot.jpg",
    inOffice: true,
    vacationDaysRemaining: 12,
    phone: "333 - 5455",
    position: "Finance Clerk",
    wfh: true,
    address: "273 Sky Dr, Kamloops BC",
  },
  {
    id: 6,
    name: "Julie Markdum",
    age: 25,
    on: false,
    img: "https://us.123rf.com/450wm/fizkes/fizkes2011/fizkes201102042/159430998-headshot-portrait-profile-picture-of-pretty-smiling-young-woman-posing-indoors-looking-at-camera-sat.jpg?ver=6",
    inOffice: true,
    vacationDaysRemaining: 6,
    phone: "353 - 9453",
    position: "Medcial Officer",
    wfh: false,
    address: "45 Lase St, Kingston ON",
  },
];
